# This is a basic workflow to help you get started with Actions

name: Test

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      DEPAY_MNEMONIC: ${{secrets.DEPAY_MNEMONIC}}
      DEPAY_RPC_URL: ${{secrets.DEPAY_RPC_URL}}
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Install packages
        run: yarn install

      # Runs a set of commands using the runners shell
      - name: Create .env file
        run: |
          echo "DEPAY_MNEMONIC=${DEPAY_MNEMONIC}" > .env,
          echo "DEPAY_RPC_URL=${DEPAY_RPC_URL}" >> .env

      - name: Run test
        run: yarn test
